<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0e5164f9-ade8-459f-91e2-85f122cea2f7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="test/**/*.cs" />
  </ItemGroup>

</Project>
